### PR TITLE
Overwrite 'n save

### LINKED ISSUE #184: Raise error instead of overwriting an existing netCDF file
During model initialization we currently check if an output file already exists in the `out_dir` location and raise a warning, but go ahead and overwrite the existing netCDF file with a new (blank) one [here](https://github.com/DeltaRCM/pyDeltaRCM/blob/620c7a8876a4ddab39b8cf36df2fc8aeb972fde7/pyDeltaRCM/init_tools.py#L501).

Instead of doing this, we should raise an error and not overwrite an existing output. Support for a "clobber" flag could be provided if desired to allow overwriting...

### LINKED ISSUE #185: Turn on checkpointing automatically if checkpoint_dt is provided
Right now you can specify a `checkpoint_dt` but if you don't explicitly toggle `save_checkpoint: True` in the yaml, checkpoint information will not be saved.

I don't think it will be terribly complicated to automatically set `save_checkpoint` to True by modifying the setter behavior for `self.checkpoint_dt`, maybe something like adding an "else" statement:

```
    @checkpoint_dt.setter
    def checkpoint_dt(self, checkpoint_dt):
        if checkpoint_dt is None:
            checkpoint_dt = self._save_dt
        else:
            self.save_checkpoint = True
        self._checkpoint_dt = checkpoint_dt
```

Probably need to look closer to make sure this will actually work for differently ordered yamls and other scenarios, etc.

### PR DESCRIPTION
**Pull request by elbeejay**
## PR to modify overwriting <s>and checkpoint saving</s> behavior

PR does <s>2</s> 1 thing<s>s</s>.

1. Adds `clobber_netcdf` as a yaml parameter with default behavior set to False. This parameter controls whether or not an existing pyDeltaRCM output file will be overwritten if a new model is initialized with the same `out_dir`. Currently we overwrite the old file and spit out a warning. Proposed default behavior raises an error before overwriting an existing file, but existing behavior can still be had (maybe useful for prototyping or testing when the same model is being initialized a bunch) by setting `clobber_netcdf` to True. Closes #184.

Edited to just make clobbering an optional parameter. Didn't want to over-complicate saving logic.

<s>2. <s>Current checkpointing behavior requires `save_checkpoint` to be explicitly set to True in order to save any checkpointing information. My opinion is that if one bothers specifying `checkpoint_dt` as a number in the yaml, then `save_checkpoint` should automatically flip to True if it wasn't already. That is just my opinion, so feel free to disagree... this would close 185.</s> Changed this to cover really the two scenarios in "conflict". 
 
The first is when `save_checkpoint: False` and `checkpoint_dt = #`. This scenario may arise when the user actually intends for a checkpoint to be saved with `checkpoint_dt` but did not actually specify `save_checkpoint` and so it took on its default value of `False`. Proposed change does not change the value of parameters but provides a warning to the user to let them know that a `checkpoint_dt` value has been specified but checkpointing is turned off.

The second is when `save_checkpoint: True` and `checkpoint_dt` is not specified. In that case, the user wishes to save a checkpoint but has not specified the frequency at which they want to save it. When this happens, we revert to the previous behavior and set `checkpoint_dt = save_dt`, but now a warning is supplied to the user telling them that this is happening. Before we did this without notifying the user or recording it...</s>

### CODE REVIEW

**Comment by amoodie** [comment]
I think 1) makes sense. No comments there :+1: 

I think 2) make sense, mostly.

My only thought is that we have a few of these "one setting overrides another" situations now, and I think that's fine, but maybe we can would feel better about the choices if we also throw a warning? At least this way, the behavior is documented in both the documentation and in the runtime.

Also, importantly, what happens in the case where I explicitly set both `checkpoint_dt: 100`, `save_checkpoint: False`? Maybe I ran the model to a point where I am happy with the checkpointed state, and I want to experiment with a few different conditions following that state, but not overwrite the checkpoint file (e.g., a spin-up run). Do I need to also remove the `checkpoint_dt`? This is an actual scenario I am working now, where I use the same "base yaml" to run a spin-up and a matrix of experiments following that resumed state. I think we need to be sure to honor the `save_checkpoint: False` if it is stated explicitly.

**Comment by elbeejay** [comment]
> My only thought is that we have a few of these "one setting overrides another" situations now, and I think that's fine, but maybe we can would feel better about the choices if we also throw a warning? At least this way, the behavior is documented in both the documentation and in the runtime.

Sure I can agree with throwing a warning. What other situations are you thinking of where one parameter supercedes another? The closest I am coming up with now is the `clobber_netcdf` which doesn't really supercede another parameter per-say, and we don't do any funny business with the subsidence settings...

> Also, importantly, what happens in the case where I explicitly set both `checkpoint_dt: 100`, `save_checkpoint: False`? Maybe I ran the model to a point where I am happy with the checkpointed state, and I want to experiment with a few different conditions following that state, but not overwrite the checkpoint file (e.g., a spin-up run). Do I need to also remove the `checkpoint_dt`?

Ya this is a good point, I agree. Maybe the solution is to *not* change the behavior or modify `save_checkpoint` in any way but instead just throw a warning when `checkpoint_dt` is explicitly specified but checkpoints will not actually get saved because `save_checkpoint` is False and vise-versa. That would at least let the user know upon initialization that `save_checkpoint` and `checkpoint_dt` are somewhat in conflict without modifying what the model does. 

>  This is an actual scenario I am working now, where I use the same "base yaml" to run a spin-up and a matrix of experiments following that resumed state. I think we need to be sure to honor the `save_checkpoint: False` if it is stated explicitly.

This is interesting and I'd never considered this use-case. Might ask you later about how you're doing that without running into some sort of `out_dir` / output file issue. I'd naively thought that to do that sort of experimentation you would want to copy the netCDF file and checkpoint data to experimental folders (which is why I probably didn't think this change would pose a problem).

**Comment by amoodie** [comment]
Sorry I kind of lost where we are on this one. I checked it out on an example that I think verifies it will work for whatever I need, so I think it's good.

If you're good, merge when ready :+1:

**Comment by elbeejay** [comment]
> Sorry I kind of lost where we are on this one. I checked it out on an example that I think verifies it will work for whatever I need, so I think it's good.
> 
> If you're good, merge when ready

Cool, I guess I'm still thinking about whether or not the added complexity to the checkpointing yaml parameters is necessary. The netCDF clobber parameter seems like a reasonable thing to implement, but I am trying to decide if I should just unwind the checkpointing changes.

**Comment by elbeejay** [comment]
Rewound this to just implement the check and toggle for netCDF clobbering. 

We can revisit the saving parameters/methods later if we find there is a need to do so.

**Pull request merged**
