### PR TITLE
Expanding pyDeltaRCM Documentation

### PR DESCRIPTION
**Pull request by elbeejay**
## Expanding the documentation

Work in progress but wanted to open this up for feedback on format more than anything. 

Our documentation currently covers the bare-bones of setting up and running a model, but lacks background information on what the model is doing, what model parameters are/mean, etc. (Relates to #4, #5, #6).

In this PR I want to propose adding a __Model Information__ section to the documentation where this information can be put. My current skeleton format is this:

```
| Model Information
| - YAML Parameters
| - Time in pyDeltaRCM
| - Hydrodynamics
| - Morphodynamics
| - Output File Format
```

In `YAML Parameters` provides links to the API reference for yaml attribute doc-strings in `model.py`. The `Hydrodynamics` section explains the methods and process by which pyDeltaRCM handles the weighted random walk. etc. etc.

## Done in this PR:

- [x] Populate and describe `YAML Parameters` in `model.py` doc-strings
   - Every model attribute has, at minimum, the short one-liner doc-string description
- [x] Add value checking to yaml parameters
   - Use the "setter" decorator to do some value checking for yaml parameters and added related unit tests
- [x] Update model internals to use the private model attributes
   - Slight speed-up, if any
   - Ran 10 timesteps on a 3km x 6km domain in triplicate with the code before switching to private model attributes and then another 3 tests afterwards, in all cases the privatized versions were faster (by <1%, but always faster)
- [x] Populate and describe `Output File Format` section
   - Brief description could be embellished / have some sort of graphic
- Caught bug in metadata, vectors were all saving `SLR` values, so corrected those to reference the proper variables
   - Added assertions to relevant unit tests to avoid issue in the future

## Not done in this PR:
Documentation explaining:
- `Model Time` vs "Simulated Time" and how to convert/work with "time"
- The reduced-complexity `Hydrodynamics`
- The reduced-complexity `Morphodynamics`

### CODE REVIEW

**Comment by amoodie** [comment]
I think an additional thing to do for the yaml parameters is to make each of the a `@property` of the `DeltaModel` class, and then all the options would be documented [here](https://deltarcm.org/pyDeltaRCM/_autosummary/pyDeltaRCM.model.DeltaModel.html#pyDeltaRCM.model.DeltaModel) and each one can link to the page you created with `YAML Parameters`. We can (and probably should) [change the sphinx setup](https://github.com/DeltaRCM/pyDeltaRCM/blob/4d19f7ff19e31683d0250ffa0f6ae67a3a126c3f/docs/source/conf.py#L67) so that only those options are documented on the `DeltaModel` doc page, and one would go to the `sed_tools` page to look at that documentation, rahter than having all inherited methods of the `DeltaModel` documented on that page. 

Having the `@property` set up for each will make the BMI wrapper and documentation therein really simple. Basically, we just set BMI model `@properties` like `sea_surface_elevation` that are wrappers to set the `DeltaModel` `@property` `H_SL`. Importantly, if the `DeltaModel` has legitimate `@property` rather that just attributes, we can actually just link to the pyDeltaRCM documentation for any option in the BMI.

**Comment by amoodie** [comment]
I should also say I'm :100: on the "high level" documentation _explaining_ the model, rather than just documenting it.

**Comment by elbeejay** [comment]
> I think an additional thing to do for the yaml parameters is to make each of the a `@property` of the `DeltaModel` class, and then all the options would be documented [here](https://deltarcm.org/pyDeltaRCM/_autosummary/pyDeltaRCM.model.DeltaModel.html#pyDeltaRCM.model.DeltaModel) and each one can link to the page you created with `YAML Parameters`. We can (and probably should) [change the sphinx setup](https://github.com/DeltaRCM/pyDeltaRCM/blob/4d19f7ff19e31683d0250ffa0f6ae67a3a126c3f/docs/source/conf.py#L67) so that only those options are documented on the `DeltaModel` doc page, and one would go to the `sed_tools` page to look at that documentation, rahter than having all inherited methods of the `DeltaModel` documented on that page.
> 
> Having the `@property` set up for each will make the BMI wrapper and documentation therein really simple. Basically, we just set BMI model `@properties` like `sea_surface_elevation` that are wrappers to set the `DeltaModel` `@property` `H_SL`. Importantly, if the `DeltaModel` has legitimate `@property` rather that just attributes, we can actually just link to the pyDeltaRCM documentation for any option in the BMI.

I thought I liked and understood this idea, but I ran into a bit of an issue when implementing this.

The impression I got, was that we'd define an `@property` for each of the yaml parameters within the `DeltaModel()` class (which is in `model.py`) and write out a doc-string that explains what the parameter is and this doc-string could then be linked for the documentation both of pyDeltaRCM and its BMI. For example, the first yaml item, `out_dir`:

```
@property
def out_dir(self, out_dir):
    """
    Description of out_dir ... 
    """
    self.out_dir = out_dir
```

Or maybe with a dedicated "setter":
```
@property
def out_dir(self):
    """
    Description of out_dir ... 
    """
    return self.out_dir

@out_dir.setter
def out_dir(self, out_dir):
    """set out_dir."""
    self.out_dir = out_dir
```

But either way it is implemented, this breaks because the model is trying to do the `setattr` looping to run through the yaml. I like the `setattr` loop system of parsing the yaml, and it seems unreasonable to swap that for an individual call for each yaml item to be set via a dedicated `@property`/"setter". I'm hoping that I am just missing something related to the relationship between the special `@property` decorator and `setattr`, but my understanding is that they both effectively do the same thing - so in that sense I am not surprised trying to "have it both ways" generates an error. 

Anyway, any thoughts are appreciated @amoodie, the idea seemed nice as a way to keep the yaml parameter definitions bound to the code and reference-able for different documentations as needed. If it seems too ugly, there isn't anything really wrong with writing markdown to describe the parameters I don't think.

**Comment by amoodie** [comment]
So, declaring the private variables works without any changes:

```
@property
def out_dir(self):
    """
    Description of out_dir ... 

    Must be a string.
    """"
    return self._out_dir

@out_dir.setter
def out_dir(self, out_dir):
    self._out_dir = out_dir
```

Then, anywhere in the model we can still access as `self.out_dir`. It may be slightly faster to access variables as `self._out_dir`, so for some paramters that are critical for being used again and again in a loop, it may make sense to change the code there to access the private variables (are there any even?)

The benefits I see to this are 1) as you said, the integrated documentation, and 2) the ability to do any validation or sanitation on the input parameters. We already do `type` checking of the input parameters during the parsing of the YAML file, but we do not do any _value_ checking, for example:


```
@property
def f_bedload(self):
    """
    Description of bedload parameter... 

    Must be between 0 and 1, inclusive.
    """"
    return self._f_bedload

@f_bedload.setter
def f_bedload(self, f_bedload):
    if (f_bedload < 0) or (f_bedload > 1):
        raise ValueError('Value for f_bedload must be between 0 and 1, inclusive')
    self._f_bedload = f_bedload
```

**Comment by elbeejay** [comment]
So I think this is ready to be merged. It doesn't do anything spectacular, but does move us in the right direction documentation-wise I think.

Went ahead and implemented some of the things @amoodie suggested:

> It may be slightly faster to access variables as self._out_dir, so for some paramters that are critical for being used again and again in a loop, it may make sense to change the code there to access the private variables (are there any even?)

I did this since it really can only help (even if minimally). My tests showed a <1% speed-up after making the parameters "private" in the model internals for a super short test simulation (10 time steps), but it *was* a slightly faster. So maybe this pays off a bit for longer runs.

> We already do type checking of the input parameters during the parsing of the YAML file, but we do not do any value checking...

Added some rudimentary value checking for the parameters I was confident about, and the associated unit tests, so this is a definite benefit to making this switch to the property-decorators and private attributes.

**Review by amoodie — APPROVED** [review]
I checked this out, compiled fine on my computer. Looks awesome. You say:

> move us in the right direction documentation-wise I think

I would say it moves us a huge step towards our goal of having helpful documentation. Awesome work.

**Pull request merged**
