### PR TITLE
Tidy up repository, initialize docs

### PR DESCRIPTION
**Pull request by amoodie**
## Changes
* code style brought up to pep8 (mostly)
* clear out some junk (`.ipynb-checkpoint` files, random file headers, `setup.py` changes)
* add assets for website
* add a `_version.py` file -- single central place to track version (not fully implemented yet, will have to do more here when we want to deploy to pypi etc)
* probably other minor housekeeping I'm forgetting
* I'd also like to change the default branch to `develop` if that's cool.

I did not change any functionality. The goal here is to just clean things up to continue moving forward from. 

## Docs
* sets up *framework* for docs.
* the docs are not complete, but this is a start

## Rename repository
I would like to rename the repository. Not sure if immediately following this PR is a good time to make that change (with a combination of another PR and some triggers on GitHub, Travis), or if we want to wait until we drop the BMI support and house it elsewhere.

## Related
#14 #2 #3 #4 #5 #6 #7
This is basically the same code as in #20, which got messed up when I attempted to reauthor commits.

### CODE REVIEW

**Review by elbeejay — APPROVED** [review]
Looks good.

**Comment by amoodie** [comment]
## Questions
To @ericbarefoot @elbeejay @ammilten -- do you folks use the [`run_pyDeltaRCM.py`](https://github.com/DeltaRCM/pyDeltaRCM_WMT/blob/develop/run_pyDeltaRCM.py), [`run_pyDeltaRCM_checkpoints.py`](https://github.com/DeltaRCM/pyDeltaRCM_WMT/blob/develop/run_pyDeltaRCM_checkpoints.py), and/or [`strat_preprocess.py`](https://github.com/DeltaRCM/pyDeltaRCM_WMT/blob/develop/strat_preprocess.py) files in the root of the repository?

## About
* I read the `strat_preprocess.py` file. and it just reads the `.nc` files, does a preservation calculation, and then saves out the strata as a new `.nc` file. I think this is a routine that belongs in 1) an optional config flag can output this strata matrix during `finalize()`, and 2) DeltaMetrics project. 
* the other two files `run_pyDeltaRCM.py` and `run_pyDeltaRCM_checkpoints.py` each just initialize the delta from `.yaml` and then run it some number of timesteps. The checkpoint file has some additional flags to save/load checkpoints.

## Proposals
* delete `strat_preprocess.py` completely, we can work it into the `finalize()` routine later, if we want to. I'll open an issue pointing to the code for preservation/convenience (it will always be in the git history).
* delete the `run_pyDeltaRCM.py` and `run_pyDeltaRCM_checkpoints.py` files. I think this type of file belongs in documentation. Plus, if we decide to take [my proposal for changing how we setup runs (with a default parameter set, and then override these with a new yaml)](https://github.com/DeltaRCM/pyDeltaRCM_WMT/issues/16#issuecomment-615386249), these files would become obsolete. I think now is a fine time to delete them; I'll open an issue pointing to the codes for preservation/convenience (they will always be in the git history)

Would like to address these ideas before merging the PR

**Comment by elbeejay** [comment]
Your interpretation of those files is correct. I think it would be good to incorporate the `strat_preprocess.py` into the `finalize()` routine. It was more of a late addition to properly create the stratigraphy with the model outputs as it was set up before.

I guess we can remove the two versions of the `run_pyDeltaRCM.py` files, but I think we should consider building in a "checkpointing" feature into the codebase so that a run that is interrupted midway for whatever reason can be re-loaded and continued.

**Comment by amoodie** [comment]
Okay, I'll just leave those files alone for now. It makes just as much sense to move them when we make changes to the yaml input workflow and the save-file output routines. I guess these are both PRs Eric is thinking about...

Anyway, I'm good to merge this if y'all are good.

**Comment by ericbarefoot** [comment]
>I guess we can remove the two versions of the run_pyDeltaRCM.py files, but I think we should consider building in a "checkpointing" feature into the codebase so that a run that is interrupted midway for whatever reason can be re-loaded and continued.

I am generally fine with the idea of deleting these files too, but at the moment, they are convenient, and it's the main way that I run the model when I'm working on it. @amoodie what would be your vision for how the user would interface with the model then? Would they write their own version of this script and run it?

**Comment by ericbarefoot** [comment]
As for `strat_preprocess.py` I haven't used it, but I like the idea of folding it into the rest of the codebase.

**Review by ericbarefoot — APPROVED** [review]
This looks good to me. Do we all need to get a deltarcm-helper, or is that something that just lives on github?

**Comment by amoodie** [comment]
> at the moment, they are convenient, and it's the main way that I run the model when I'm working on it. 

Cool, that's exactly what I asked above, and wanted to know. If you are currently using them we should :100: leave them until we get a new setup fully implemented.

> @amoodie what would be your vision for how the user would interface with the model then? Would they write their own version of this script and run it?

We can set up the package with some `__main__.py` magic and then users can:
```python
import pyDeltaRCM
pyDeltaRCM.run_from_config(/path/to/Run10232.yaml)
```
which would create the full final output files at a located defined in `Run10232.yaml`, according to all the config defined in `Run10232.yaml`, but only timstepping 10 times, regardless of what is written in the config. Of course the length of the timestep may be set in the config...
 
Alternatively, a more manual manipulation (i.e., what the automated workflow above calls):
```python
import pyDeltaRCM
mdl = pyDeltaRCM.init_from_config(/path/to/Run10232.yaml)
for i in range(10):
    mdl.run_one_timestep()
mdl.finalize()
mdl.write_to_file()
```
which would create the full final output files at a located defined in `Run10232.yaml`, according to all the config (including timestepping configs) defined in `Run10232.yaml`. 

Alternatively alternatively, we can set up a hook from bash:
```bash
pyDeltaRCM --config /path/to/Run10232.yaml
```

There's lots of options. So, the user need not write their own script to run the module, but they could if they wanted to do something non-standard.

**Comment by amoodie** [comment]
I'm going to open an issue to continue the config discussion.

**Comment by amoodie** [comment]
> Do we all need to get a deltarcm-helper, or is that something that just lives on github?

Sorry didn't see your question @ericbarefoot . No you don't need your own. You can always author changes as someone else with `git commit -m "message" --author <deltarcm-helper deltarcm-helper@users.noreply.github.com>` but they won't be "verified". In theory I can author a commit as you too, but it wouldn't be verified (this is one of the "services" github offers). I just used it to do the pep8 related changes. Not my own changes to docs etc.

The deltarcm-helper account is literally just a github account. I can provide you the credentials privately any time you need them. I use it to provide authorization to the repositories for the continuous integration apps, so that I don't have to put my own repo access into the CI.

**Pull request merged**
