### PR TITLE
Strip bmi

### PR DESCRIPTION
**Pull request by amoodie**
This PR removes all of the references to the BMI that I could find.

Additionally, I added a line to the README that points to the BMI_pyDeltaRCM repository, where we now support the BMI as a wrapper around the pypi version of this package.

*IMPORTANT:* if y'all approve of this PR, I would like to remove the `_WMT` at the end of the repository. I will do this immediately after we merge this PR. I will then create 1) another PR that updates all of the links and text in this repository, and 2) update the `deltarcm.org` website accordingly. In the meantime, I believe GitHub will automatically redirect requests at the old repo name to the new repo name. You will want to update the `remote`s on your local `git` accordingly.

### CODE REVIEW

**Review by elbeejay — APPROVED** [review]
Not sure where/how to leave this comment, but we don't need to keep the `parameters.yaml` or `deltaRCM.yaml.tmpl` files in the BMI_pyDeltaRCM repo? They don't seem to have found a home there yet and I wouldn't want them to disappear as they seem to define many of the BMI variables. So not relevant to this PR, just don't want to merge this and lose track of those files.

Similar note as above for the `run_pyDeltaRCM_as_BMI.py` file.

Otherwise this seems to accomplish what it sets out to, the BMI bits are stripped out and tests/everything else are passing. Works for me. :+1:

**Comment by amoodie** [comment]
> but we don't need to keep the `parameters.yaml` or `deltaRCM.yaml.tmpl` files in the `BMI_pyDeltaRCM` repo?

It's a good question. When I read the BMI 2.0 specifications, I couldn't find anything about it. The files will never be deleted from the .git history, so will always be recoverable based on the commit hash.

I'll do these steps today:
* open an issue in `BMI_pyDeltaRCM` that asks whether we need these files.
* include a permalink to the files on github in that issue
* open a question on the [`csdms/help-desk`](https://github.com/csdms/help-desk) repo asking about these files

**Comment by elbeejay** [comment]
> > but we don't need to keep the `parameters.yaml` or `deltaRCM.yaml.tmpl` files in the `BMI_pyDeltaRCM` repo?
> 
> It's a good question. When I read the BMI 2.0 specifications, I couldn't find anything about it. The files will never be deleted from the .git history, so will always be recoverable based on the commit hash.
> 
> I'll do these steps today:
> 
> * open an issue in `BMI_pyDeltaRCM` that asks whether we need these files.
> * include a permalink to the files on github in that issue
> * open a question on the [`csdms/help-desk`](https://github.com/csdms/help-desk) repo asking about these files

Sounds good, at least that'll keep us from forgetting they ever existed (even if the git history never forgets, we might).

**Comment by amoodie** [comment]
* [See question in the help-desk here](https://github.com/csdms/help-desk/issues/32)
* [See issue in `BMI_pyDeltaRCM` here](https://github.com/DeltaRCM/BMI_pyDeltaRCM/issues/2)

**Review by ericbarefoot — APPROVED** [review]
This is great. I don't see anything obvious that would prevent this from being a go. Just let me know when you get the repo updated with the new name and I'll update my local pointers. 

Thanks for the great effort on this! I am stoked to have these two things separated from each other. It will make the project work much more streamlined.

**Pull request merged**
